id: I7D5312A7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T13:25:08+00:00'
last_modified: '2022-06-08T10:47:50.010537+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W11225
  title: ཉམས་མགུར་ཆུ་ཟླའི་གར་ཕྲེང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    388C:
      image_group_id: I1KG9411
      title: ''
      total_pages: 456
      order: 1
      base_file: 388C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
