id: P009407
initial_creation_type: ocr
source_metadata:
  id: bdr:W11225
  title: ཉམས་མགུར་ཆུ་ཟླའི་གར་ཕྲེང་།
  author: ''
  volumes:
    e00d0ecc6cbf4abc848784c5a993ea1a:
      image_group_id: I1KG9411
      title: ''
      volume_number: 1
      total_pages: 456
      base_file: v001.txt
